---
name: libedax4dart_example
publish_to: none

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  ffi: ^2.1.5
  libedax4dart:
    path: ..

dev_dependencies:
  analyzer: ^10.0.2
  pedantic_sensuikan1973: ^5.16.0
