---
# See: https://dart.dev/tools/pub/publishing

name: libedax4dart
version: 7.64.0
description: Dart wrapper for libedax. With using libedax4dart, you can execute functions equivalent to edax.
homepage: https://github.com/sensuikan1973/libedax4dart
repository: https://github.com/sensuikan1973/libedax4dart

environment:
  sdk: '>=3.9.0 <4.0.0' # See: https://dart.dev/null-safety#enable-null-safety

dependencies:
  ffi: ^2.2.0
  meta: ^1.18.1

dev_dependencies:
  analyzer: ^10.1.0
  coverage: ^1.15.0 # See: https://github.com/dart-lang/test/issues/1265
  ffigen: ^20.1.1
  pana: ^0.23.10
  pedantic_sensuikan1973: ^5.16.0
  test: ^1.29.0

topics:
  - reversi
  - edax
