---
name: Upgrade Dart Dependencies

on:
  schedule:
    - cron: '0 21 * * 5'
  workflow_dispatch:

jobs:
  upgrade_dart_dependencies:
    runs-on: macos-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6
      - uses: dart-lang/setup-dart@v1

      - name: setup llvm for ffigen
        run: brew install llvm

      - name: upgrade dependencies on lib
        run: dart pub upgrade --major-versions --tighten
      - name: run ffigen
        run: |
          libedax_build_command="make universal_osx_libbuild" dst="." ./scripts/build_libedax.sh
          dart run ffigen --config ffigen.yaml --verbose severe
      - name: upgrade dependencies on example
        run: cd example && dart pub upgrade --major-versions --tighten

      # See: https://github.com/peter-evans/create-pull-request/tree/master#reference-example
      - name: create PR
        id: create_pull_request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.PAT }} # See: https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#triggering-further-workflow-runs
          # See: https://github.com/peter-evans/create-pull-request/issues/593
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit-message: upgrade dart dependencies
          title: upgrade dart dependencies
          body: |
            Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request)

            ---
            See: https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#triggering-further-workflow-runs
          branch: upgrade_dart_dependencies
          delete-branch: true
          labels: dependencies

      - name: enable auto-merge
        if: ${{ steps.create_pull_request.outputs.pull-request-number != '' }}
        run: gh pr merge ${{ steps.create_pull_request.outputs.pull-request-number }} --squash --auto
        env:
          GH_TOKEN: ${{ secrets.PAT }}
